services:
  - type: web
    name: impresiones-sos-api
    env: docker
    rootDir: server
    plan: free
    autoDeploy: true
    # Render define PORT; nuestro Dockerfile expone 10000, pero usaremos el que Render provea
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: BASE_URL
        value: https://impresiones-sos-api.onrender.com
